### ISSUE TITLE
Facing issues when loding the maskdepth_model.pth checkpoint

### ISSUE THREAD

**Issue by Kenjamin99** [adobe-research/layered-depth-refinement#10]
I read your wonderful paper, and believe it will be helpful for my research. But I enconter some issues when loding the `maskdepth_model.pth` checkpoint. Here is the error
`Traceback (most recent call last):
  File "./test.py", line 104, in <module>
    load_ckpt(model, args.ckpt_path, device=device, strict=True)
  File "./test.py", line 52, in load_ckpt
    ckpt = torch.load(ckpt_path, map_location=lambda storage, loc: storage)
  File "/home/zzl/.conda/envs/zzl_torch_cuda_12/lib/python3.8/site-packages/torch/serialization.py", line 1028, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/zzl/.conda/envs/zzl_torch_cuda_12/lib/python3.8/site-packages/torch/serialization.py", line 1246, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.`

**Comment by tqhtqhtqhgo** [comment]
Same problem, how do you solve it?

**Comment by FUJI-W** [comment]
have you solve it？
